#!/bin/bash

exists() {
  [ `type -t $1`"" == 'function' ]
}

apt_get_install() {
  command "/usr/bin/apt" install "$@"
}

apt_get_remove() {
  command "/usr/bin/apt" remove "$@"
}

apt_get_update() {
  command "/usr/bin/apt" update "$@"
}

apt_get_upgrade() {
  command "/usr/bin/apt" upgrade "$@"
}

apt_cache_search() {
  command "/usr/bin/apt" search "$@"
}

apt_cache_show() {
  command "/usr/bin/apt" show "$@"
}

apt_get_autoremove() {
  command "/usr/bin/apt" autoremove "$@"
}

apt_get_purge() {
  command "/usr/bin/apt" purge "$@"
}

cmd=$1
subcmd=$2
shift 2
if exists "${cmd/-/_}_${subcmd}"; then
  "${cmd/-/_}_$subcmd" "$@"
else
  case $cmd in
    apt-get)
      cmd="/usr/bin/apt-get"
      ;;
    apt-cache)
      cmd="/usr/bin/apt-cache"
      ;;
  esac
  command "${cmd}" "${subcmd}" "$@"
fi
